### ISSUE TITLE
Template Refresh: Legislation Tracker

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#116]
Relevant files:

- [ ] page-legislation-tracker.php
- [ ] taxonomy-bill-type.php
- [ ] taxonomy-session.php
